export const employeesInfo = [
  {
    id: '2',
    name: 'Tom Cruise',
    email: 'john.doe@example.com',
    department: 'Founder & Chairman',
    startDate: '2021-01-01',
    salary: 50000,
    img: '/person/Tom-Cruise.png',
    twitter: 'http://twitter.com',
    instagram: 'https://www.instagram.com',
    linkedin: 'https://www.linkedin.com',
  },
  {
    id: '3',
    name: 'Emma Watson',
    email: 'jane.doe@example.com',
    department: 'Managing Director',
    startDate: '2020-12-01',
    salary: 40000,
    img: '/person/Emma-Watson.png',
    twitter: 'http://twitter.com',
    instagram: 'https://www.instagram.com',
    linkedin: 'https://www.linkedin.com',
  },
  {
    id: '4',
    name: 'Will Smith',
    email: 'will.smith@example.com',
    department: 'Product Designer',
    startDate: '2020-11-01',
    salary: 35000,
    img: '/person/Will-Smith.png',
    twitter: 'http://twitter.com',
    instagram: 'https://www.instagram.com',
    linkedin: 'https://www.linkedin.com',
  },
  {
    id: '1',
    name: 'Will Smith',
    email: 'will.smith@example.com',
    department: 'Product Designer',
    startDate: '2020-11-01',
    salary: 35000,
    img: '/person/Will-Smith.png',
    twitter: 'http://twitter.com',
    instagram: 'https://www.instagram.com',
    linkedin: 'https://www.linkedin.com',
  },
  {
    id: '5',
    name: 'Tom Cruise',
    email: 'john.doe@example.com',
    department: 'Founder & Chairman',
    startDate: '2021-01-01',
    salary: 50000,
    img: '/person/Tom-Cruise.png',
    twitter: 'http://twitter.com',
    instagram: 'https://www.instagram.com',
    linkedin: 'https://www.linkedin.com',
  },
];
